name: Sync to GitLab

on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Sync to GitLab
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        
        # Remplacez cette URL par votre URL GitLab exacte
        git remote add gitlab https://oauth2:${GITLAB_TOKEN}@gitlab.com/Claire29200/projet-cesizen.git
        
        git push gitlab --all --force
        git push gitlab --tags --force
